# Config for running the InferenceRecipe in generate.py to generate output from an LLM
#
# To launch, run the following command from root torchtune directory:
#    tune run generate --config generation

# Model arguments
model:
  _component_: torchtune.models.llama3.qlora_llama3_8b
  lora_attn_modules: ["q_proj", "v_proj", "k_proj", "output_proj"]
  apply_lora_to_mlp: True
  apply_lora_to_output: False
  lora_rank: 8
  lora_alpha: 16

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: tmp/Meta-Llama-3-8B-Instruct/original/
  checkpoint_files: [consolidated.00.pth]
  recipe_checkpoint: null
  output_dir: tmp/Meta-Llama-3-8B-Instruct/
  model_type: LLAMA3

# Training
epochs: 1
max_steps_per_epoch: null
gradient_accumulation_steps: 16
compile: False
resume_from_checkpoint: False

# Environment
device: cuda
dtype: bf16
enable_activation_checkpointing: True
seed: null
shuffle: True
batch_size: 2

# Tokenizer arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: tmp/Meta-Llama-3-8B-Instruct/original/tokenizer.model

# Generation arguments; defaults taken from gpt-fast
prompt: "Olá!"
instruct_template: null
chat_format: null
max_new_tokens: 300
temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300

quantizer: null