# Model Arguments
model:
  _component_: torchtune.models.llama3.llama3_8b

checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: tmp/Meta-Llama-3-8B-Instruct/
  checkpoint_files: [meta_model_0.pt]
  # adapter_checkpoint: adapter_0.pt
  recipe_checkpoint: null
  output_dir: tmp/Meta-Llama-3-8B-Instruct/
  model_type: LLAMA3

device: cuda
dtype: bf16

seed: 1234

# Tokenizer arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: tmp/Meta-Llama-3-8B-Instruct/original/tokenizer.model

# Generation arguments; defaults taken from gpt-fast
prompt: "Hello, my name is"
max_new_tokens: 256
temperature: 0.6 # 0.8 and 0.6 are popular values to try
top_k: 300

quantizer: null